In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import files
uploaded=files.upload()
a=next(iter(uploaded))

Saving anomaly_detection.csv to anomaly_detection.csv

In [3]:
df=pd.read_csv(a)
df

,timestamp,user_id,login_duration_min,data_accessed_MB,files_downloaded,remote_access
0,2025-04-06 04:00:00,user_023,33.417560,229.196409,3,No
1,2025-04-11 23:00:00,user_040,11.951179,221.816183,4,No
2,2025-04-19 07:00:00,user_044,40.490092,178.529723,4,No
3,2025-04-19 09:00:00,user_005,15.915387,227.164901,5,No
4,2025-04-06 00:00:00,user_012,8.761043,175.528028,4,Yes
...,...,...,...,...,...,...
500,2025-04-09 02:00:00,user_009,28.929696,217.136267,3,No
501,2025-04-13 05:00:00,user_020,25.881230,166.418832,4,No
502,2025-04-01 17:00:00,user_002,26.146864,231.033605,1,No
503,2025-04-07 03:00:00,user_015,35.144388,308.162736,4,No
504,2025-04-07 19:00:00,user_029,43.686316,123.840655,2,No

In [7]:
df.describe()

       login_duration_min  data_accessed_MB  files_downloaded
count          505.000000        505.000000        505.000000
mean            30.673913        231.012570          3.384158
std             17.802305        335.673082          5.674272
min              3.000000          5.000000          0.000000
25%             22.742562        172.226144          2.000000
50%             29.809838        206.278823          3.000000
75%             36.296288        238.020733          4.000000
max            300.000000       5000.000000        100.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   timestamp               505 non-null    object
 1   user_id                 505 non-null    object
 2   login_duration_min      505 non-null    float64
 3   data_accessed_MB        505 non-null    float64
 4   files_downloaded        505 non-null    int64
 5   remote_access           505 non-null    object
 6   login_duration_minIQR   505 non-null    bool
 7   data_accessed_MBIQR     505 non-null    bool
 8   files_downloadedIQR     505 non-null    bool
 9   login_duration_min_IQR  505 non-null    bool
 10  data_accessed_MB_IQR    505 non-null    bool
 11  files_downloaded_IQR    505 non-null    bool
dtypes: bool(6), float64(2), int64(1), object(3)
memory usage: 26.8+ KB

In [9]:
df.duplicated().sum()

np.int64(0)

In [14]:
#Using IQR[Inter-Quartile Ranges] Method Approach
features = [
    'login_duration_min',
    'data_accessed_MB',
    'files_downloaded'
]

for col in features:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df[col + '_anomaly_IQR'] = (
        (df[col] < lower) | (df[col] > upper)
    )
df.drop(columns=["login_duration_minIQR","data_accessed_MBIQR",	"files_downloadedIQR","login_duration_min_IQR","data_accessed_MB_IQR",	"files_downloaded_IQR","login_duration_min_anoamly_IQR","data_accessed_MB_anoamly_IQR","files_downloaded_anoamly_IQR"], inplace=True)

In [18]:
df

,timestamp,user_id,login_duration_min,data_accessed_MB,files_downloaded,remote_access,login_duration_min_anomaly_IQR,data_accessed_MB_anomaly_IQR,files_downloaded_anomaly_IQR,iqr_any_anomaly
0,2025-04-06 04:00:00,user_023,33.417560,229.196409,3,No,False,False,False,False
1,2025-04-11 23:00:00,user_040,11.951179,221.816183,4,No,False,False,False,False
2,2025-04-19 07:00:00,user_044,40.490092,178.529723,4,No,False,False,False,False
3,2025-04-19 09:00:00,user_005,15.915387,227.164901,5,No,False,False,False,False
4,2025-04-06 00:00:00,user_012,8.761043,175.528028,4,Yes,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
500,2025-04-09 02:00:00,user_009,28.929696,217.136267,3,No,False,False,False,False
501,2025-04-13 05:00:00,user_020,25.881230,166.418832,4,No,False,False,False,False
502,2025-04-01 17:00:00,user_002,26.146864,231.033605,1,No,False,False,False,False
503,2025-04-07 03:00:00,user_015,35.144388,308.162736,4,No,False,False,False,False
504,2025-04-07 19:00:00,user_029,43.686316,123.840655,2,No,False,False,False,False

In [16]:
df['iqr_any_anomaly'] = (
    df['login_duration_min_anomaly_IQR'] |
    df['data_accessed_MB_anomaly_IQR'] |
    df['files_downloaded_anomaly_IQR']
)
df

,timestamp,user_id,login_duration_min,data_accessed_MB,files_downloaded,remote_access,login_duration_min_anomaly_IQR,data_accessed_MB_anomaly_IQR,files_downloaded_anomaly_IQR,iqr_any_anomaly
0,2025-04-06 04:00:00,user_023,33.417560,229.196409,3,No,False,False,False,False
1,2025-04-11 23:00:00,user_040,11.951179,221.816183,4,No,False,False,False,False
2,2025-04-19 07:00:00,user_044,40.490092,178.529723,4,No,False,False,False,False
3,2025-04-19 09:00:00,user_005,15.915387,227.164901,5,No,False,False,False,False
4,2025-04-06 00:00:00,user_012,8.761043,175.528028,4,Yes,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
500,2025-04-09 02:00:00,user_009,28.929696,217.136267,3,No,False,False,False,False
501,2025-04-13 05:00:00,user_020,25.881230,166.418832,4,No,False,False,False,False
502,2025-04-01 17:00:00,user_002,26.146864,231.033605,1,No,False,False,False,False
503,2025-04-07 03:00:00,user_015,35.144388,308.162736,4,No,False,False,False,False
504,2025-04-07 19:00:00,user_029,43.686316,123.840655,2,No,False,False,False,False

In [19]:
df['iqr_any_anomaly'].value_counts()

iqr_any_anomaly
False    493
True      12
Name: count, dtype: int64

In [20]:
df[df['iqr_any_anomaly'] == True]

,timestamp,user_id,login_duration_min,data_accessed_MB,files_downloaded,remote_access,login_duration_min_anomaly_IQR,data_accessed_MB_anomaly_IQR,files_downloaded_anomaly_IQR,iqr_any_anomaly
36,2025-04-13 11:00:00,user_008,50.754008,57.572869,7,No,False,True,False,True
73,2025-04-20 06:00:00,user_026,31.708654,190.735617,8,Yes,False,False,True,True
79,2025-04-18 00:00:00,user_033,200.000000,5.000000,100,No,True,True,True,True
83,2025-04-15 00:00:00,user_036,300.000000,5000.000000,50,Yes,True,True,True,True
191,2025-04-19 21:00:00,user_050,41.033019,262.387104,8,No,False,False,True,True
196,2025-04-19 01:00:00,user_006,26.904536,222.023737,9,No,False,False,True,True
246,2025-04-06 06:00:00,user_037,39.504238,229.532742,8,No,False,False,True,True
251,2025-04-17 00:00:00,user_032,120.000000,4000.000000,60,Yes,True,True,True,True
303,2025-04-10 00:00:00,user_002,60.788808,120.804859,2,No,True,False,False,True
314,2025-04-19 00:00:00,user_045,3.000000,4500.000000,0,Yes,False,True,False,True
355,2025-04-16 00:00:00,user_025,5.000000,30.000000,0,Yes,False,True,False,True
406,2025-04-15 03:00:00,user_008,20.778347,55.187231,4,Yes,False,True,False,True

In [21]:
features = ['login_duration_min', 'data_accessed_MB', 'files_downloaded']
X = df[features]

In [22]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [23]:
from sklearn.ensemble import IsolationForest

iso = IsolationForest(
    n_estimators=100,
    contamination=0.05,  # assume ~5% anomalies
    random_state=42
)

df['iso_flag'] = iso.fit_predict(X_scaled)

In [25]:
df['iso_anomaly'] = df['iso_flag'] == -1
df

,timestamp,user_id,login_duration_min,data_accessed_MB,files_downloaded,remote_access,login_duration_min_anomaly_IQR,data_accessed_MB_anomaly_IQR,files_downloaded_anomaly_IQR,iqr_any_anomaly,iso_flag,iso_anomaly
0,2025-04-06 04:00:00,user_023,33.417560,229.196409,3,No,False,False,False,False,1,False
1,2025-04-11 23:00:00,user_040,11.951179,221.816183,4,No,False,False,False,False,1,False
2,2025-04-19 07:00:00,user_044,40.490092,178.529723,4,No,False,False,False,False,1,False
3,2025-04-19 09:00:00,user_005,15.915387,227.164901,5,No,False,False,False,False,1,False
4,2025-04-06 00:00:00,user_012,8.761043,175.528028,4,Yes,False,False,False,False,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
500,2025-04-09 02:00:00,user_009,28.929696,217.136267,3,No,False,False,False,False,1,False
501,2025-04-13 05:00:00,user_020,25.881230,166.418832,4,No,False,False,False,False,1,False
502,2025-04-01 17:00:00,user_002,26.146864,231.033605,1,No,False,False,False,False,1,False
503,2025-04-07 03:00:00,user_015,35.144388,308.162736,4,No,False,False,False,False,1,False
504,2025-04-07 19:00:00,user_029,43.686316,123.840655,2,No,False,False,False,False,1,False

In [26]:
df['iso_anomaly'].sum()

np.int64(26)

In [28]:
comparison = df[['iqr_any_anomaly', 'iso_anomaly']]
comparison.value_counts()

iqr_any_anomaly  iso_anomaly
False            False          478
                 True            15
True             True            11
                 False            1
Name: count, dtype: int64

In [29]:
suspects = df[df['iqr_any_anomaly'] & df['iso_anomaly']]
suspects

,timestamp,user_id,login_duration_min,data_accessed_MB,files_downloaded,remote_access,login_duration_min_anomaly_IQR,data_accessed_MB_anomaly_IQR,files_downloaded_anomaly_IQR,iqr_any_anomaly,iso_flag,iso_anomaly
36,2025-04-13 11:00:00,user_008,50.754008,57.572869,7,No,False,True,False,True,-1,True
79,2025-04-18 00:00:00,user_033,200.000000,5.000000,100,No,True,True,True,True,-1,True
83,2025-04-15 00:00:00,user_036,300.000000,5000.000000,50,Yes,True,True,True,True,-1,True
191,2025-04-19 21:00:00,user_050,41.033019,262.387104,8,No,False,False,True,True,-1,True
196,2025-04-19 01:00:00,user_006,26.904536,222.023737,9,No,False,False,True,True,-1,True
246,2025-04-06 06:00:00,user_037,39.504238,229.532742,8,No,False,False,True,True,-1,True
251,2025-04-17 00:00:00,user_032,120.000000,4000.000000,60,Yes,True,True,True,True,-1,True
303,2025-04-10 00:00:00,user_002,60.788808,120.804859,2,No,True,False,False,True,-1,True
314,2025-04-19 00:00:00,user_045,3.000000,4500.000000,0,Yes,False,True,False,True,-1,True
355,2025-04-16 00:00:00,user_025,5.000000,30.000000,0,Yes,False,True,False,True,-1,True
406,2025-04-15 03:00:00,user_008,20.778347,55.187231,4,Yes,False,True,False,True,-1,True

In [31]:
df['iso_score'] = iso.decision_function(X_scaled)
df.sort_values('iso_score').head(5)

,timestamp,user_id,login_duration_min,data_accessed_MB,files_downloaded,remote_access,login_duration_min_anomaly_IQR,data_accessed_MB_anomaly_IQR,files_downloaded_anomaly_IQR,iqr_any_anomaly,iso_flag,iso_anomaly,iso_score
83,2025-04-15 00:00:00,user_036,300.0,5000.0,50,Yes,True,True,True,True,-1,True,-0.345531
251,2025-04-17 00:00:00,user_032,120.0,4000.0,60,Yes,True,True,True,True,-1,True,-0.316379
79,2025-04-18 00:00:00,user_033,200.0,5.0,100,No,True,True,True,True,-1,True,-0.299917
314,2025-04-19 00:00:00,user_045,3.0,4500.0,0,Yes,False,True,False,True,-1,True,-0.234745
355,2025-04-16 00:00:00,user_025,5.0,30.0,0,Yes,False,True,False,True,-1,True,-0.144315