In [ ]:
from google.colab import files
uploaded=files.upload()
a=next(iter(uploaded))

Saving customer_data.csv to customer_data.csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("customer_data.csv")

In [ ]:
df.head()

,CustomerID,Name,Age,Gender,Country,SignupDate,LastLogin,TotalPurchase,PreferredDevice,Email
0,e3e70682-c209-4cac-a29f-6fbed82c07cd,Christopher Williams,63.0,Male,USA,2021-12-22,2023-09-12,2141.15,dasktop,margaret03@bullock.info
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Kevin Hopkins,42.0,Female,UK,2023-04-21,2024-06-28,2863.67,NaN,tammy76@mcintyre.org
2,eb1167b3-67a9-4378-bc65-c1e582e2e662,Sonya Stafford,76.0,Femlae,UK,2020-09-16,2023-06-13,2427.18,NaN,lauramichael@hotmail.com
3,f7c1bd87-4da5-4709-9471-3d60c8a70639,Matthew Schmidt,53.0,Unknown,Indai,2021-05-16,2024-12-15,5986.07,moblie,@example.com
4,e443df78-9558-467f-9ba9-1faf7a024204,Kristen Banks,74.0,NaN,UK,2022-04-14,2025-01-08,3374.72,dasktop,blacknicole@smith-lewis.com

In [ ]:
df = df.drop_duplicates()
df

,CustomerID,Name,Age,Gender,Country,SignupDate,LastLogin,TotalPurchase,PreferredDevice,Email
0,e3e70682-c209-4cac-a29f-6fbed82c07cd,Christopher Williams,63.0,Male,USA,2021-12-22,2023-09-12,2141.15,dasktop,margaret03@bullock.info
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Kevin Hopkins,42.0,Female,UK,2023-04-21,2024-06-28,2863.67,NaN,tammy76@mcintyre.org
2,eb1167b3-67a9-4378-bc65-c1e582e2e662,Sonya Stafford,76.0,Femlae,UK,2020-09-16,2023-06-13,2427.18,NaN,lauramichael@hotmail.com
3,f7c1bd87-4da5-4709-9471-3d60c8a70639,Matthew Schmidt,53.0,Unknown,Indai,2021-05-16,2024-12-15,5986.07,moblie,@example.com
4,e443df78-9558-467f-9ba9-1faf7a024204,Kristen Banks,74.0,NaN,UK,2022-04-14,2025-01-08,3374.72,dasktop,blacknicole@smith-lewis.com
...,...,...,...,...,...,...,...,...,...,...
49995,310fbdbb-917a-429f-b433-943cbf12a183,Elizabeth Parker,27.0,NaN,Canda,2022-11-15,2024-08-21,7775.01,moblie,christopher66@nguyen-colon.com
49996,4aed72d8-5e4d-4474-beeb-4a2b96021ca8,Tammy Baker,57.0,Unknown,Indai,2022-05-23,2023-12-17,8696.38,moblie,nicholas65@marquez-simmons.biz
49997,a7c61286-1c15-4374-9a1f-58024b0e1de5,Barbara Wood,64.0,Female,USA,2023-08-04,2023-08-08,9620.75,moblie,tadams@gmail.com
49998,3f02b0a7-e5df-44af-903e-37070954affb,Wayne Montgomery,32.0,Female,India,2023-02-11,2023-08-04,1712.46,NaN,teresadean@gmail.com
49999,7a9cc65c-576a-40bd-87ef-ae5269a84714,Michael Richardson,28.0,mle,NaN,2023-10-28,2025-03-07,8606.62,dasktop,clarson@knight-harrington.org

In [ ]:
df["Name"].str.strip("1234567890._/")

0        Christopher Williams
1               Kevin Hopkins
2              Sonya Stafford
3             Matthew Schmidt
4               Kristen Banks
                 ...
49995        Elizabeth Parker
49996             Tammy Baker
49997            Barbara Wood
49998        Wayne Montgomery
49999      Michael Richardson
Name: Name, Length: 50000, dtype: object

In [ ]:
df.head(10)

,CustomerID,Name,Age,Gender,Country,SignupDate,LastLogin,TotalPurchase,PreferredDevice,Email
0,e3e70682-c209-4cac-a29f-6fbed82c07cd,Christopher Williams,63.0,Male,USA,2021-12-22,2023-09-12,2141.15,dasktop,margaret03@bullock.info
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Kevin Hopkins,42.0,Female,UK,2023-04-21,2024-06-28,2863.67,NaN,tammy76@mcintyre.org
2,eb1167b3-67a9-4378-bc65-c1e582e2e662,Sonya Stafford,76.0,Femlae,UK,2020-09-16,2023-06-13,2427.18,NaN,lauramichael@hotmail.com
3,f7c1bd87-4da5-4709-9471-3d60c8a70639,Matthew Schmidt,53.0,Unknown,Indai,2021-05-16,2024-12-15,5986.07,moblie,@example.com
4,e443df78-9558-467f-9ba9-1faf7a024204,Kristen Banks,74.0,NaN,UK,2022-04-14,2025-01-08,3374.72,dasktop,blacknicole@smith-lewis.com
5,23a7711a-8133-4876-b7eb-dcd9e87a1613,Andrew Adams,74.0,NaN,USA,2022-03-09,2023-07-13,740.75,moblie,james83@henderson.com
6,1846d424-c17c-4279-a3c6-612f48268673,7061,51.0,Female,UK,2021-01-16,2024-09-23,7702.33,dasktop,woodsusan@yahoo.com
7,fcbd04c3-4021-4ef7-8ca5-a5a19e4d6e3c,Amanda Webster,38.0,Unknown,USA,2020-11-26,2023-11-21,5103.92,mobile,jason95@collins.com
8,b4862b21-fb97-4435-8856-1712e8e5216a,David Holt,63.0,NaN,Germany,2021-01-07,2024-04-16,1666.40,mobile,tammythomas@brown.org
9,259f4329-e6f4-490b-9a16-4106cf6a659e,Cameron Guerrero,29.0,mle,UK,2023-11-14,2024-12-15,7062.40,dasktop,murraydylan@gmail.com

In [ ]:
df["num"] = df["Name"].str.isnumeric()
df.head(10)

,CustomerID,Name,Age,Gender,Country,SignupDate,LastLogin,TotalPurchase,PreferredDevice,Email,num
0,e3e70682-c209-4cac-a29f-6fbed82c07cd,Christopher Williams,63.0,Male,USA,2021-12-22,2023-09-12,2141.15,dasktop,margaret03@bullock.info,False
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Kevin Hopkins,42.0,Female,UK,2023-04-21,2024-06-28,2863.67,NaN,tammy76@mcintyre.org,False
2,eb1167b3-67a9-4378-bc65-c1e582e2e662,Sonya Stafford,76.0,Femlae,UK,2020-09-16,2023-06-13,2427.18,NaN,lauramichael@hotmail.com,False
3,f7c1bd87-4da5-4709-9471-3d60c8a70639,Matthew Schmidt,53.0,Unknown,Indai,2021-05-16,2024-12-15,5986.07,moblie,@example.com,False
4,e443df78-9558-467f-9ba9-1faf7a024204,Kristen Banks,74.0,NaN,UK,2022-04-14,2025-01-08,3374.72,dasktop,blacknicole@smith-lewis.com,False
5,23a7711a-8133-4876-b7eb-dcd9e87a1613,Andrew Adams,74.0,NaN,USA,2022-03-09,2023-07-13,740.75,moblie,james83@henderson.com,False
6,1846d424-c17c-4279-a3c6-612f48268673,7061,51.0,Female,UK,2021-01-16,2024-09-23,7702.33,dasktop,woodsusan@yahoo.com,True
7,fcbd04c3-4021-4ef7-8ca5-a5a19e4d6e3c,Amanda Webster,38.0,Unknown,USA,2020-11-26,2023-11-21,5103.92,mobile,jason95@collins.com,False
8,b4862b21-fb97-4435-8856-1712e8e5216a,David Holt,63.0,NaN,Germany,2021-01-07,2024-04-16,1666.40,mobile,tammythomas@brown.org,False
9,259f4329-e6f4-490b-9a16-4106cf6a659e,Cameron Guerrero,29.0,mle,UK,2023-11-14,2024-12-15,7062.40,dasktop,murraydylan@gmail.com,False

In [ ]:
df.loc[df["Name"].astype(str).str.isnumeric(), "Name"] = np.nan
df.head(10)

,CustomerID,Name,Age,Gender,Country,SignupDate,LastLogin,TotalPurchase,PreferredDevice,Email,num
0,e3e70682-c209-4cac-a29f-6fbed82c07cd,Christopher Williams,63.0,Male,USA,2021-12-22,2023-09-12,2141.15,dasktop,margaret03@bullock.info,False
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Kevin Hopkins,42.0,Female,UK,2023-04-21,2024-06-28,2863.67,NaN,tammy76@mcintyre.org,False
2,eb1167b3-67a9-4378-bc65-c1e582e2e662,Sonya Stafford,76.0,Femlae,UK,2020-09-16,2023-06-13,2427.18,NaN,lauramichael@hotmail.com,False
3,f7c1bd87-4da5-4709-9471-3d60c8a70639,Matthew Schmidt,53.0,Unknown,Indai,2021-05-16,2024-12-15,5986.07,moblie,@example.com,False
4,e443df78-9558-467f-9ba9-1faf7a024204,Kristen Banks,74.0,NaN,UK,2022-04-14,2025-01-08,3374.72,dasktop,blacknicole@smith-lewis.com,False
5,23a7711a-8133-4876-b7eb-dcd9e87a1613,Andrew Adams,74.0,NaN,USA,2022-03-09,2023-07-13,740.75,moblie,james83@henderson.com,False
6,1846d424-c17c-4279-a3c6-612f48268673,NaN,51.0,Female,UK,2021-01-16,2024-09-23,7702.33,dasktop,woodsusan@yahoo.com,True
7,fcbd04c3-4021-4ef7-8ca5-a5a19e4d6e3c,Amanda Webster,38.0,Unknown,USA,2020-11-26,2023-11-21,5103.92,mobile,jason95@collins.com,False
8,b4862b21-fb97-4435-8856-1712e8e5216a,David Holt,63.0,NaN,Germany,2021-01-07,2024-04-16,1666.40,mobile,tammythomas@brown.org,False
9,259f4329-e6f4-490b-9a16-4106cf6a659e,Cameron Guerrero,29.0,mle,UK,2023-11-14,2024-12-15,7062.40,dasktop,murraydylan@gmail.com,False

In [ ]:
df["Gender"] = df["Gender"].str.replace('Femlae','Female')
df["Gender"] = df["Gender"].str.replace('mle','Male')
df.head(10)

,CustomerID,Name,Age,Gender,Country,SignupDate,LastLogin,TotalPurchase,PreferredDevice,Email,num
0,e3e70682-c209-4cac-a29f-6fbed82c07cd,Christopher Williams,63.0,Male,USA,2021-12-22,2023-09-12,2141.15,dasktop,margaret03@bullock.info,False
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Kevin Hopkins,42.0,Female,UK,2023-04-21,2024-06-28,2863.67,NaN,tammy76@mcintyre.org,False
2,eb1167b3-67a9-4378-bc65-c1e582e2e662,Sonya Stafford,76.0,Female,UK,2020-09-16,2023-06-13,2427.18,NaN,lauramichael@hotmail.com,False
3,f7c1bd87-4da5-4709-9471-3d60c8a70639,Matthew Schmidt,53.0,Unknown,Indai,2021-05-16,2024-12-15,5986.07,moblie,@example.com,False
4,e443df78-9558-467f-9ba9-1faf7a024204,Kristen Banks,74.0,NaN,UK,2022-04-14,2025-01-08,3374.72,dasktop,blacknicole@smith-lewis.com,False
5,23a7711a-8133-4876-b7eb-dcd9e87a1613,Andrew Adams,74.0,NaN,USA,2022-03-09,2023-07-13,740.75,moblie,james83@henderson.com,False
6,1846d424-c17c-4279-a3c6-612f48268673,NaN,51.0,Female,UK,2021-01-16,2024-09-23,7702.33,dasktop,woodsusan@yahoo.com,True
7,fcbd04c3-4021-4ef7-8ca5-a5a19e4d6e3c,Amanda Webster,38.0,Unknown,USA,2020-11-26,2023-11-21,5103.92,mobile,jason95@collins.com,False
8,b4862b21-fb97-4435-8856-1712e8e5216a,David Holt,63.0,NaN,Germany,2021-01-07,2024-04-16,1666.40,mobile,tammythomas@brown.org,False
9,259f4329-e6f4-490b-9a16-4106cf6a659e,Cameron Guerrero,29.0,Male,UK,2023-11-14,2024-12-15,7062.40,dasktop,murraydylan@gmail.com,False

In [ ]:
df = df.drop("num",axis=1)
df

,CustomerID,Name,Age,Gender,Country,SignupDate,LastLogin,TotalPurchase,PreferredDevice,Email
0,e3e70682-c209-4cac-a29f-6fbed82c07cd,Christopher Williams,63.0,Male,USA,2021-12-22,2023-09-12,2141.15,dasktop,margaret03@bullock.info
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Kevin Hopkins,42.0,Female,UK,2023-04-21,2024-06-28,2863.67,NaN,tammy76@mcintyre.org
2,eb1167b3-67a9-4378-bc65-c1e582e2e662,Sonya Stafford,76.0,Female,UK,2020-09-16,2023-06-13,2427.18,NaN,lauramichael@hotmail.com
3,f7c1bd87-4da5-4709-9471-3d60c8a70639,Matthew Schmidt,53.0,Unknown,Indai,2021-05-16,2024-12-15,5986.07,moblie,@example.com
4,e443df78-9558-467f-9ba9-1faf7a024204,Kristen Banks,74.0,NaN,UK,2022-04-14,2025-01-08,3374.72,dasktop,blacknicole@smith-lewis.com
...,...,...,...,...,...,...,...,...,...,...
49995,310fbdbb-917a-429f-b433-943cbf12a183,Elizabeth Parker,27.0,NaN,Canda,2022-11-15,2024-08-21,7775.01,moblie,christopher66@nguyen-colon.com
49996,4aed72d8-5e4d-4474-beeb-4a2b96021ca8,Tammy Baker,57.0,Unknown,Indai,2022-05-23,2023-12-17,8696.38,moblie,nicholas65@marquez-simmons.biz
49997,a7c61286-1c15-4374-9a1f-58024b0e1de5,Barbara Wood,64.0,Female,USA,2023-08-04,2023-08-08,9620.75,moblie,tadams@gmail.com
49998,3f02b0a7-e5df-44af-903e-37070954affb,Wayne Montgomery,32.0,Female,India,2023-02-11,2023-08-04,1712.46,NaN,teresadean@gmail.com
49999,7a9cc65c-576a-40bd-87ef-ae5269a84714,Michael Richardson,28.0,Male,NaN,2023-10-28,2025-03-07,8606.62,dasktop,clarson@knight-harrington.org

In [ ]:
df["Country"] = df["Country"].str.replace('Indai','India')
df["Country"] = df["Country"].str.replace('Canda','Canada')
df

,CustomerID,Name,Age,Gender,Country,SignupDate,LastLogin,TotalPurchase,PreferredDevice,Email
0,e3e70682-c209-4cac-a29f-6fbed82c07cd,Christopher Williams,63.0,Male,USA,2021-12-22,2023-09-12,2141.15,dasktop,margaret03@bullock.info
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Kevin Hopkins,42.0,Female,UK,2023-04-21,2024-06-28,2863.67,NaN,tammy76@mcintyre.org
2,eb1167b3-67a9-4378-bc65-c1e582e2e662,Sonya Stafford,76.0,Female,UK,2020-09-16,2023-06-13,2427.18,NaN,lauramichael@hotmail.com
3,f7c1bd87-4da5-4709-9471-3d60c8a70639,Matthew Schmidt,53.0,Unknown,India,2021-05-16,2024-12-15,5986.07,moblie,@example.com
4,e443df78-9558-467f-9ba9-1faf7a024204,Kristen Banks,74.0,NaN,UK,2022-04-14,2025-01-08,3374.72,dasktop,blacknicole@smith-lewis.com
...,...,...,...,...,...,...,...,...,...,...
49995,310fbdbb-917a-429f-b433-943cbf12a183,Elizabeth Parker,27.0,NaN,Canada,2022-11-15,2024-08-21,7775.01,moblie,christopher66@nguyen-colon.com
49996,4aed72d8-5e4d-4474-beeb-4a2b96021ca8,Tammy Baker,57.0,Unknown,India,2022-05-23,2023-12-17,8696.38,moblie,nicholas65@marquez-simmons.biz
49997,a7c61286-1c15-4374-9a1f-58024b0e1de5,Barbara Wood,64.0,Female,USA,2023-08-04,2023-08-08,9620.75,moblie,tadams@gmail.com
49998,3f02b0a7-e5df-44af-903e-37070954affb,Wayne Montgomery,32.0,Female,India,2023-02-11,2023-08-04,1712.46,NaN,teresadean@gmail.com
49999,7a9cc65c-576a-40bd-87ef-ae5269a84714,Michael Richardson,28.0,Male,NaN,2023-10-28,2025-03-07,8606.62,dasktop,clarson@knight-harrington.org

In [ ]:
df["PreferredDevice"]=df["PreferredDevice"].str.replace('dasktop','Desktop')
df["PreferredDevice"]=df["PreferredDevice"].str.replace('moblie','Mobile')
df

,CustomerID,Name,Age,Gender,Country,SignupDate,LastLogin,TotalPurchase,PreferredDevice,Email
0,e3e70682-c209-4cac-a29f-6fbed82c07cd,Christopher Williams,63.0,Male,USA,2021-12-22,2023-09-12,2141.15,Desktop,margaret03@bullock.info
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Kevin Hopkins,42.0,Female,UK,2023-04-21,2024-06-28,2863.67,NaN,tammy76@mcintyre.org
2,eb1167b3-67a9-4378-bc65-c1e582e2e662,Sonya Stafford,76.0,Female,UK,2020-09-16,2023-06-13,2427.18,NaN,lauramichael@hotmail.com
3,f7c1bd87-4da5-4709-9471-3d60c8a70639,Matthew Schmidt,53.0,Unknown,India,2021-05-16,2024-12-15,5986.07,Mobile,@example.com
4,e443df78-9558-467f-9ba9-1faf7a024204,Kristen Banks,74.0,NaN,UK,2022-04-14,2025-01-08,3374.72,Desktop,blacknicole@smith-lewis.com
...,...,...,...,...,...,...,...,...,...,...
49995,310fbdbb-917a-429f-b433-943cbf12a183,Elizabeth Parker,27.0,NaN,Canada,2022-11-15,2024-08-21,7775.01,Mobile,christopher66@nguyen-colon.com
49996,4aed72d8-5e4d-4474-beeb-4a2b96021ca8,Tammy Baker,57.0,Unknown,India,2022-05-23,2023-12-17,8696.38,Mobile,nicholas65@marquez-simmons.biz
49997,a7c61286-1c15-4374-9a1f-58024b0e1de5,Barbara Wood,64.0,Female,USA,2023-08-04,2023-08-08,9620.75,Mobile,tadams@gmail.com
49998,3f02b0a7-e5df-44af-903e-37070954affb,Wayne Montgomery,32.0,Female,India,2023-02-11,2023-08-04,1712.46,NaN,teresadean@gmail.com
49999,7a9cc65c-576a-40bd-87ef-ae5269a84714,Michael Richardson,28.0,Male,NaN,2023-10-28,2025-03-07,8606.62,Desktop,clarson@knight-harrington.org

In [ ]:
df["TotalPurchase"] = df["TotalPurchase"].abs()

In [ ]:
for i in df.index:
    if df.loc[i, "Age"] < 0 or df.loc[i, "Age"] > 100:
        df.loc[i, "Age"] = np.nan
df

,CustomerID,Name,Age,Gender,Country,SignupDate,LastLogin,TotalPurchase,PreferredDevice,Email
0,e3e70682-c209-4cac-a29f-6fbed82c07cd,Christopher Williams,63.0,Male,USA,2021-12-22,2023-09-12,2141.15,Desktop,margaret03@bullock.info
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Kevin Hopkins,42.0,Female,UK,2023-04-21,2024-06-28,2863.67,NaN,tammy76@mcintyre.org
2,eb1167b3-67a9-4378-bc65-c1e582e2e662,Sonya Stafford,76.0,Female,UK,2020-09-16,2023-06-13,2427.18,NaN,lauramichael@hotmail.com
3,f7c1bd87-4da5-4709-9471-3d60c8a70639,Matthew Schmidt,53.0,Unknown,India,2021-05-16,2024-12-15,5986.07,Mobile,@example.com
4,e443df78-9558-467f-9ba9-1faf7a024204,Kristen Banks,74.0,NaN,UK,2022-04-14,2025-01-08,3374.72,Desktop,blacknicole@smith-lewis.com
...,...,...,...,...,...,...,...,...,...,...
49995,310fbdbb-917a-429f-b433-943cbf12a183,Elizabeth Parker,27.0,NaN,Canada,2022-11-15,2024-08-21,7775.01,Mobile,christopher66@nguyen-colon.com
49996,4aed72d8-5e4d-4474-beeb-4a2b96021ca8,Tammy Baker,57.0,Unknown,India,2022-05-23,2023-12-17,8696.38,Mobile,nicholas65@marquez-simmons.biz
49997,a7c61286-1c15-4374-9a1f-58024b0e1de5,Barbara Wood,64.0,Female,USA,2023-08-04,2023-08-08,9620.75,Mobile,tadams@gmail.com
49998,3f02b0a7-e5df-44af-903e-37070954affb,Wayne Montgomery,32.0,Female,India,2023-02-11,2023-08-04,1712.46,NaN,teresadean@gmail.com
49999,7a9cc65c-576a-40bd-87ef-ae5269a84714,Michael Richardson,28.0,Male,NaN,2023-10-28,2025-03-07,8606.62,Desktop,clarson@knight-harrington.org

In [ ]:
df = df.dropna(subset=['CustomerID', 'Email', 'TotalPurchase'])
df

,CustomerID,Name,Age,Gender,Country,SignupDate,LastLogin,TotalPurchase,PreferredDevice,Email
0,e3e70682-c209-4cac-a29f-6fbed82c07cd,Christopher Williams,63.0,Male,USA,2021-12-22,2023-09-12,2141.15,Desktop,margaret03@bullock.info
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Kevin Hopkins,42.0,Female,UK,2023-04-21,2024-06-28,2863.67,NaN,tammy76@mcintyre.org
2,eb1167b3-67a9-4378-bc65-c1e582e2e662,Sonya Stafford,76.0,Female,UK,2020-09-16,2023-06-13,2427.18,NaN,lauramichael@hotmail.com
3,f7c1bd87-4da5-4709-9471-3d60c8a70639,Matthew Schmidt,53.0,Unknown,India,2021-05-16,2024-12-15,5986.07,Mobile,@example.com
4,e443df78-9558-467f-9ba9-1faf7a024204,Kristen Banks,74.0,NaN,UK,2022-04-14,2025-01-08,3374.72,Desktop,blacknicole@smith-lewis.com
...,...,...,...,...,...,...,...,...,...,...
49995,310fbdbb-917a-429f-b433-943cbf12a183,Elizabeth Parker,27.0,NaN,Canada,2022-11-15,2024-08-21,7775.01,Mobile,christopher66@nguyen-colon.com
49996,4aed72d8-5e4d-4474-beeb-4a2b96021ca8,Tammy Baker,57.0,Unknown,India,2022-05-23,2023-12-17,8696.38,Mobile,nicholas65@marquez-simmons.biz
49997,a7c61286-1c15-4374-9a1f-58024b0e1de5,Barbara Wood,64.0,Female,USA,2023-08-04,2023-08-08,9620.75,Mobile,tadams@gmail.com
49998,3f02b0a7-e5df-44af-903e-37070954affb,Wayne Montgomery,32.0,Female,India,2023-02-11,2023-08-04,1712.46,NaN,teresadean@gmail.com
49999,7a9cc65c-576a-40bd-87ef-ae5269a84714,Michael Richardson,28.0,Male,NaN,2023-10-28,2025-03-07,8606.62,Desktop,clarson@knight-harrington.org

In [ ]:
df = df.reset_index(drop=True)
df

,CustomerID,Name,Age,Gender,Country,SignupDate,LastLogin,TotalPurchase,PreferredDevice,Email
0,e3e70682-c209-4cac-a29f-6fbed82c07cd,Christopher Williams,63.0,Male,USA,2021-12-22,2023-09-12,2141.15,Desktop,margaret03@bullock.info
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Kevin Hopkins,42.0,Female,UK,2023-04-21,2024-06-28,2863.67,NaN,tammy76@mcintyre.org
2,eb1167b3-67a9-4378-bc65-c1e582e2e662,Sonya Stafford,76.0,Female,UK,2020-09-16,2023-06-13,2427.18,NaN,lauramichael@hotmail.com
3,f7c1bd87-4da5-4709-9471-3d60c8a70639,Matthew Schmidt,53.0,Unknown,India,2021-05-16,2024-12-15,5986.07,Mobile,@example.com
4,e443df78-9558-467f-9ba9-1faf7a024204,Kristen Banks,74.0,NaN,UK,2022-04-14,2025-01-08,3374.72,Desktop,blacknicole@smith-lewis.com
...,...,...,...,...,...,...,...,...,...,...
45980,310fbdbb-917a-429f-b433-943cbf12a183,Elizabeth Parker,27.0,NaN,Canada,2022-11-15,2024-08-21,7775.01,Mobile,christopher66@nguyen-colon.com
45981,4aed72d8-5e4d-4474-beeb-4a2b96021ca8,Tammy Baker,57.0,Unknown,India,2022-05-23,2023-12-17,8696.38,Mobile,nicholas65@marquez-simmons.biz
45982,a7c61286-1c15-4374-9a1f-58024b0e1de5,Barbara Wood,64.0,Female,USA,2023-08-04,2023-08-08,9620.75,Mobile,tadams@gmail.com
45983,3f02b0a7-e5df-44af-903e-37070954affb,Wayne Montgomery,32.0,Female,India,2023-02-11,2023-08-04,1712.46,NaN,teresadean@gmail.com
45984,7a9cc65c-576a-40bd-87ef-ae5269a84714,Michael Richardson,28.0,Male,NaN,2023-10-28,2025-03-07,8606.62,Desktop,clarson@knight-harrington.org

In [ ]:
df['Age']=df['Age'].fillna(df['Age'].median())
df['Gender']=df['Gender'].fillna('Unknown')
df['PreferredDevice']=df['PreferredDevice'].fillna('Unknown')
df['Country']=df['Country'].fillna('Unknown')
df

/tmp/ipython-input-3823224596.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age']=df['Age'].fillna(df['Age'].median())
/tmp/ipython-input-3823224596.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gender']=df['Gender'].fillna('Unknown')
/tmp/ipython-input-3823224596.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['PreferredDevice']=df['PreferredDevice'].fillna('Unknown')
/tmp/ipython-input-3823224596.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Country']=df['Country'].fillna('Unknown')

,CustomerID,Name,Age,Gender,Country,SignupDate,LastLogin,TotalPurchase,PreferredDevice,Email
0,e3e70682-c209-4cac-a29f-6fbed82c07cd,Christopher Williams,63.0,Male,USA,2021-12-22,2023-09-12,2141.15,Desktop,margaret03@bullock.info
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Kevin Hopkins,42.0,Female,UK,2023-04-21,2024-06-28,2863.67,Unknown,tammy76@mcintyre.org
2,eb1167b3-67a9-4378-bc65-c1e582e2e662,Sonya Stafford,76.0,Female,UK,2020-09-16,2023-06-13,2427.18,Unknown,lauramichael@hotmail.com
3,f7c1bd87-4da5-4709-9471-3d60c8a70639,Matthew Schmidt,53.0,Unknown,India,2021-05-16,2024-12-15,5986.07,Mobile,NaN
4,e443df78-9558-467f-9ba9-1faf7a024204,Kristen Banks,74.0,Unknown,UK,2022-04-14,2025-01-08,3374.72,Desktop,blacknicole@smith-lewis.com
...,...,...,...,...,...,...,...,...,...,...
45980,310fbdbb-917a-429f-b433-943cbf12a183,Elizabeth Parker,27.0,Unknown,Canada,2022-11-15,2024-08-21,7775.01,Mobile,christopher66@nguyen-colon.com
45981,4aed72d8-5e4d-4474-beeb-4a2b96021ca8,Tammy Baker,57.0,Unknown,India,2022-05-23,2023-12-17,8696.38,Mobile,nicholas65@marquez-simmons.biz
45982,a7c61286-1c15-4374-9a1f-58024b0e1de5,Barbara Wood,64.0,Female,USA,2023-08-04,2023-08-08,9620.75,Mobile,tadams@gmail.com
45983,3f02b0a7-e5df-44af-903e-37070954affb,Wayne Montgomery,32.0,Female,India,2023-02-11,2023-08-04,1712.46,Unknown,teresadean@gmail.com
45984,7a9cc65c-576a-40bd-87ef-ae5269a84714,Michael Richardson,28.0,Male,Unknown,2023-10-28,2025-03-07,8606.62,Desktop,clarson@knight-harrington.org

In [ ]:
df['SignupDate'] = pd.to_datetime(df['SignupDate'], errors='coerce')
df['LastLogin'] = pd.to_datetime(df['LastLogin'], errors='coerce')
df

,CustomerID,Name,Age,Gender,Country,SignupDate,LastLogin,TotalPurchase,PreferredDevice,Email
0,e3e70682-c209-4cac-a29f-6fbed82c07cd,Christopher Williams,63.0,Male,USA,2021-12-22,2023-09-12,2141.15,Desktop,margaret03@bullock.info
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Kevin Hopkins,42.0,Female,UK,2023-04-21,2024-06-28,2863.67,Unknown,tammy76@mcintyre.org
2,eb1167b3-67a9-4378-bc65-c1e582e2e662,Sonya Stafford,76.0,Female,UK,2020-09-16,2023-06-13,2427.18,Unknown,lauramichael@hotmail.com
3,f7c1bd87-4da5-4709-9471-3d60c8a70639,Matthew Schmidt,53.0,Unknown,India,2021-05-16,2024-12-15,5986.07,Mobile,@example.com
4,e443df78-9558-467f-9ba9-1faf7a024204,Kristen Banks,74.0,Unknown,UK,2022-04-14,2025-01-08,3374.72,Desktop,blacknicole@smith-lewis.com
...,...,...,...,...,...,...,...,...,...,...
45980,310fbdbb-917a-429f-b433-943cbf12a183,Elizabeth Parker,27.0,Unknown,Canada,2022-11-15,2024-08-21,7775.01,Mobile,christopher66@nguyen-colon.com
45981,4aed72d8-5e4d-4474-beeb-4a2b96021ca8,Tammy Baker,57.0,Unknown,India,2022-05-23,2023-12-17,8696.38,Mobile,nicholas65@marquez-simmons.biz
45982,a7c61286-1c15-4374-9a1f-58024b0e1de5,Barbara Wood,64.0,Female,USA,2023-08-04,2023-08-08,9620.75,Mobile,tadams@gmail.com
45983,3f02b0a7-e5df-44af-903e-37070954affb,Wayne Montgomery,32.0,Female,India,2023-02-11,2023-08-04,1712.46,Unknown,teresadean@gmail.com
45984,7a9cc65c-576a-40bd-87ef-ae5269a84714,Michael Richardson,28.0,Male,NaN,2023-10-28,2025-03-07,8606.62,Desktop,clarson@knight-harrington.org

In [ ]:
df = df[df['Email'].str.contains('invalidemail.com', na=False) == False]
df

,CustomerID,Name,Age,Gender,Country,SignupDate,LastLogin,TotalPurchase,PreferredDevice,Email
0,e3e70682-c209-4cac-a29f-6fbed82c07cd,Christopher Williams,63.0,Male,USA,2021-12-22,2023-09-12,2141.15,Desktop,margaret03@bullock.info
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Kevin Hopkins,42.0,Female,UK,2023-04-21,2024-06-28,2863.67,Unknown,tammy76@mcintyre.org
2,eb1167b3-67a9-4378-bc65-c1e582e2e662,Sonya Stafford,76.0,Female,UK,2020-09-16,2023-06-13,2427.18,Unknown,lauramichael@hotmail.com
3,f7c1bd87-4da5-4709-9471-3d60c8a70639,Matthew Schmidt,53.0,Unknown,India,2021-05-16,2024-12-15,5986.07,Mobile,@example.com
4,e443df78-9558-467f-9ba9-1faf7a024204,Kristen Banks,74.0,Unknown,UK,2022-04-14,2025-01-08,3374.72,Desktop,blacknicole@smith-lewis.com
...,...,...,...,...,...,...,...,...,...,...
45980,310fbdbb-917a-429f-b433-943cbf12a183,Elizabeth Parker,27.0,Unknown,Canada,2022-11-15,2024-08-21,7775.01,Mobile,christopher66@nguyen-colon.com
45981,4aed72d8-5e4d-4474-beeb-4a2b96021ca8,Tammy Baker,57.0,Unknown,India,2022-05-23,2023-12-17,8696.38,Mobile,nicholas65@marquez-simmons.biz
45982,a7c61286-1c15-4374-9a1f-58024b0e1de5,Barbara Wood,64.0,Female,USA,2023-08-04,2023-08-08,9620.75,Mobile,tadams@gmail.com
45983,3f02b0a7-e5df-44af-903e-37070954affb,Wayne Montgomery,32.0,Female,India,2023-02-11,2023-08-04,1712.46,Unknown,teresadean@gmail.com
45984,7a9cc65c-576a-40bd-87ef-ae5269a84714,Michael Richardson,28.0,Male,NaN,2023-10-28,2025-03-07,8606.62,Desktop,clarson@knight-harrington.org

In [ ]:
df['Email'].str.contains(r'^[^@]+@[^@]+\.[^@]+$')

0         True
1         True
2         True
3        False
4         True
         ...
45980     True
45981     True
45982     True
45983     True
45984     True
Name: Email, Length: 44842, dtype: bool

In [ ]:

valid_email = df['Email'].str.contains(r'^[^@]+@[^@]+\.[^@]+$', na=False)
df.loc[~valid_email, 'Email'] = np.nan

df

,CustomerID,Name,Age,Gender,Country,SignupDate,LastLogin,TotalPurchase,PreferredDevice,Email
0,e3e70682-c209-4cac-a29f-6fbed82c07cd,Christopher Williams,63.0,Male,USA,2021-12-22,2023-09-12,2141.15,Desktop,margaret03@bullock.info
1,f728b4fa-4248-4e3a-8a5d-2f346baa9455,Kevin Hopkins,42.0,Female,UK,2023-04-21,2024-06-28,2863.67,Unknown,tammy76@mcintyre.org
2,eb1167b3-67a9-4378-bc65-c1e582e2e662,Sonya Stafford,76.0,Female,UK,2020-09-16,2023-06-13,2427.18,Unknown,lauramichael@hotmail.com
3,f7c1bd87-4da5-4709-9471-3d60c8a70639,Matthew Schmidt,53.0,Unknown,India,2021-05-16,2024-12-15,5986.07,Mobile,NaN
4,e443df78-9558-467f-9ba9-1faf7a024204,Kristen Banks,74.0,Unknown,UK,2022-04-14,2025-01-08,3374.72,Desktop,blacknicole@smith-lewis.com
...,...,...,...,...,...,...,...,...,...,...
45980,310fbdbb-917a-429f-b433-943cbf12a183,Elizabeth Parker,27.0,Unknown,Canada,2022-11-15,2024-08-21,7775.01,Mobile,christopher66@nguyen-colon.com
45981,4aed72d8-5e4d-4474-beeb-4a2b96021ca8,Tammy Baker,57.0,Unknown,India,2022-05-23,2023-12-17,8696.38,Mobile,nicholas65@marquez-simmons.biz
45982,a7c61286-1c15-4374-9a1f-58024b0e1de5,Barbara Wood,64.0,Female,USA,2023-08-04,2023-08-08,9620.75,Mobile,tadams@gmail.com
45983,3f02b0a7-e5df-44af-903e-37070954affb,Wayne Montgomery,32.0,Female,India,2023-02-11,2023-08-04,1712.46,Unknown,teresadean@gmail.com
45984,7a9cc65c-576a-40bd-87ef-ae5269a84714,Michael Richardson,28.0,Male,NaN,2023-10-28,2025-03-07,8606.62,Desktop,clarson@knight-harrington.org

In [ ]:
df.to_csv("cleaned_customer_data.csv", index=False)

from google.colab import files
files.download("cleaned_customer_data.csv")