In [1]:
from google.colab import files
uploaded = files.upload()
a=next(iter(uploaded))

Saving data.csv to data.csv

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [3]:
df = pd.read_csv(a)
df.head(10)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN
5,843786,M,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,...,23.75,103.40,741.6,0.1791,0.5249,0.5355,0.1741,0.3985,0.12440,NaN
6,844359,M,18.25,19.98,119.60,1040.0,0.09463,0.10900,0.11270,0.07400,...,27.66,153.20,1606.0,0.1442,0.2576,0.3784,0.1932,0.3063,0.08368,NaN
7,84458202,M,13.71,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.05985,...,28.14,110.60,897.0,0.1654,0.3682,0.2678,0.1556,0.3196,0.11510,NaN
8,844981,M,13.00,21.82,87.50,519.8,0.12730,0.19320,0.18590,0.09353,...,30.73,106.20,739.3,0.1703,0.5401,0.5390,0.2060,0.4378,0.10720,NaN
9,84501001,M,12.46,24.04,83.97,475.9,0.11860,0.23960,0.22730,0.08543,...,40.68,97.65,711.4,0.1853,1.0580,1.1050,0.2210,0.4366,0.20750,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [5]:
df = df.drop(columns='Unnamed: 32', axis=1)
df = df.drop(columns='id', axis=1)
df.head(10)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678
5,M,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,0.2087,...,15.47,23.75,103.40,741.6,0.1791,0.5249,0.5355,0.1741,0.3985,0.12440
6,M,18.25,19.98,119.60,1040.0,0.09463,0.10900,0.11270,0.07400,0.1794,...,22.88,27.66,153.20,1606.0,0.1442,0.2576,0.3784,0.1932,0.3063,0.08368
7,M,13.71,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.05985,0.2196,...,17.06,28.14,110.60,897.0,0.1654,0.3682,0.2678,0.1556,0.3196,0.11510
8,M,13.00,21.82,87.50,519.8,0.12730,0.19320,0.18590,0.09353,0.2350,...,15.49,30.73,106.20,739.3,0.1703,0.5401,0.5390,0.2060,0.4378,0.10720
9,M,12.46,24.04,83.97,475.9,0.11860,0.23960,0.22730,0.08543,0.2030,...,15.09,40.68,97.65,711.4,0.1853,1.0580,1.1050,0.2210,0.4366,0.20750

In [6]:
df["diagnosis"] = df["diagnosis"].map({"M": 1, "B": 0})

X = df.drop(columns=["diagnosis"])
y = df["diagnosis"]

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

KNN = KNeighborsClassifier(n_neighbors=5)
KNN.fit(X_train, y_train)

y_pred = KNN.predict(X_test)
# base metrics are stored in a dictionary
metrics = {
    "accuracy": accuracy_score(y_test, y_pred),
    "precision": precision_score(y_test, y_pred),
    "recall": recall_score(y_test, y_pred),
    "f1": f1_score(y_test, y_pred)
}

print("Metrics:", metrics)

Metrics: {'accuracy': 0.9473684210526315, 'precision': 0.9302325581395349, 'recall': 0.9302325581395349, 'f1': 0.9302325581395349}

In [11]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

X = df.drop(columns=["diagnosis"])
y = df["diagnosis"]

results = []

features = X.columns

for feature in features:

    X_drop = X.drop(columns=[feature])


    X_train, X_test, y_train, y_test = train_test_split(X_drop, y, test_size=0.2, random_state=42)

    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    knn = KNeighborsClassifier(n_neighbors=5)
    knn.fit(X_train, y_train)

    y_pred = knn.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    results.append({
        "Removed Feature": feature,
        "Accuracy": acc,
        "Precision": prec,
        "Recall": rec,
        "F1": f1
    })
# for easy analysis of metrics,i just stored this in a dataframe
ablation_results = pd.DataFrame(results)
print(ablation_results)

            Removed Feature  Accuracy  Precision    Recall        F1
0               radius_mean  0.947368   0.930233  0.930233  0.930233
1              texture_mean  0.956140   0.952381  0.930233  0.941176
2            perimeter_mean  0.947368   0.930233  0.930233  0.930233
3                 area_mean  0.947368   0.930233  0.930233  0.930233
4           smoothness_mean  0.964912   0.953488  0.953488  0.953488
5          compactness_mean  0.956140   0.952381  0.930233  0.941176
6            concavity_mean  0.947368   0.930233  0.930233  0.930233
7       concave points_mean  0.947368   0.930233  0.930233  0.930233
8             symmetry_mean  0.947368   0.930233  0.930233  0.930233
9    fractal_dimension_mean  0.947368   0.930233  0.930233  0.930233
10                radius_se  0.947368   0.930233  0.930233  0.930233
11               texture_se  0.956140   0.952381  0.930233  0.941176
12             perimeter_se  0.956140   0.931818  0.953488  0.942529
13                  area_se  0.947368   0.930233  0.930233  0.930233
14            smoothness_se  0.947368   0.930233  0.930233  0.930233
15           compactness_se  0.947368   0.930233  0.930233  0.930233
16             concavity_se  0.947368   0.930233  0.930233  0.930233
17        concave points_se  0.956140   0.952381  0.930233  0.941176
18              symmetry_se  0.964912   0.953488  0.953488  0.953488
19     fractal_dimension_se  0.956140   0.931818  0.953488  0.942529
20             radius_worst  0.947368   0.930233  0.930233  0.930233
21            texture_worst  0.947368   0.930233  0.930233  0.930233
22          perimeter_worst  0.947368   0.930233  0.930233  0.930233
23               area_worst  0.947368   0.930233  0.930233  0.930233
24         smoothness_worst  0.956140   0.952381  0.930233  0.941176
25        compactness_worst  0.956140   0.952381  0.930233  0.941176
26          concavity_worst  0.947368   0.930233  0.930233  0.930233
27     concave points_worst  0.956140   0.952381  0.930233  0.941176
28           symmetry_worst  0.956140   0.952381  0.930233  0.941176
29  fractal_dimension_worst  0.947368   0.930233  0.930233  0.930233

In [13]:
ablation_results["Accuracy Drop"] = metrics['accuracy'] - ablation_results["Accuracy"]
ablation_results = ablation_results.sort_values(by="Accuracy Drop", ascending=False)

print(ablation_results)

            Removed Feature  Accuracy  Precision    Recall        F1  \
0               radius_mean  0.947368   0.930233  0.930233  0.930233
2            perimeter_mean  0.947368   0.930233  0.930233  0.930233
3                 area_mean  0.947368   0.930233  0.930233  0.930233
8             symmetry_mean  0.947368   0.930233  0.930233  0.930233
7       concave points_mean  0.947368   0.930233  0.930233  0.930233
6            concavity_mean  0.947368   0.930233  0.930233  0.930233
10                radius_se  0.947368   0.930233  0.930233  0.930233
13                  area_se  0.947368   0.930233  0.930233  0.930233
9    fractal_dimension_mean  0.947368   0.930233  0.930233  0.930233
20             radius_worst  0.947368   0.930233  0.930233  0.930233
21            texture_worst  0.947368   0.930233  0.930233  0.930233
16             concavity_se  0.947368   0.930233  0.930233  0.930233
15           compactness_se  0.947368   0.930233  0.930233  0.930233
14            smoothness_se  0.947368   0.930233  0.930233  0.930233
26          concavity_worst  0.947368   0.930233  0.930233  0.930233
29  fractal_dimension_worst  0.947368   0.930233  0.930233  0.930233
23               area_worst  0.947368   0.930233  0.930233  0.930233
22          perimeter_worst  0.947368   0.930233  0.930233  0.930233
1              texture_mean  0.956140   0.952381  0.930233  0.941176
12             perimeter_se  0.956140   0.931818  0.953488  0.942529
5          compactness_mean  0.956140   0.952381  0.930233  0.941176
11               texture_se  0.956140   0.952381  0.930233  0.941176
27     concave points_worst  0.956140   0.952381  0.930233  0.941176
25        compactness_worst  0.956140   0.952381  0.930233  0.941176
17        concave points_se  0.956140   0.952381  0.930233  0.941176
19     fractal_dimension_se  0.956140   0.931818  0.953488  0.942529
28           symmetry_worst  0.956140   0.952381  0.930233  0.941176
24         smoothness_worst  0.956140   0.952381  0.930233  0.941176
4           smoothness_mean  0.964912   0.953488  0.953488  0.953488
18              symmetry_se  0.964912   0.953488  0.953488  0.953488

    Accuracy Drop
0        0.000000
2        0.000000
3        0.000000
8        0.000000
7        0.000000
6        0.000000
10       0.000000
13       0.000000
9        0.000000
20       0.000000
21       0.000000
16       0.000000
15       0.000000
14       0.000000
26       0.000000
29       0.000000
23       0.000000
22       0.000000
1       -0.008772
12      -0.008772
5       -0.008772
11      -0.008772
27      -0.008772
25      -0.008772
17      -0.008772
19      -0.008772
28      -0.008772
24      -0.008772
4       -0.017544
18      -0.017544